### ISSUE TITLE
Iterate Through the Keys of an Object with a for...in Statement

### ISSUE THREAD

**Issue by danlimao** [danlimao/Trouble-with-Codes#13]
let users = {
  Alan: {
    age: 27,
    online: false
  },
  Jeff: {
    age: 32,
    online: true
  },
  Sarah: {
    age: 48,
    online: false
  },
  Ryan: {
    age: 19,
    online: true
  }
};

function countOnline(obj) {
  // change code below this line
  let count = 0

  for (let user in users) {
    if (users.user.online) {
      count++
    }
  }
  return count
  // change code above this line
}

console.log(countOnline(users));

**Comment by madnilo** [comment]
Okay, your code is ALMOST there. :)

If you console.log(user) inside your "for" loop, you will notice that user is a string with the name of each property of the main object. Try doing that:
```js
for (let user in users) {
  console.log(user) // it will print "Alan", and then "Jeff", and then...
}
```

Now, on your if you are trying to access the property "online" for each user, which is the correct idea, but the execution is wrong. See:

```js
//the way you're doing
if (users.user.online) { //this is expecting an object that looks like this: users{ user:{ online: true } }
  count++
}
```

See? Since you're directly using user with dot notation, javascript understands that you're trying to access "user" property of the object "users". You have to use bracket notation to accomplish what you want, which is access the object's properties dynamically, like this:

```js
//the way you should do, using bracket notation
if (users[user].online) { //this is expecting an object that looks like this: users{ name_of_user:{ online: true } }
  count++
}
```

You can see other ways of doing the same thing in here: https://zellwk.com/blog/looping-through-js-objects/

Keep it up.

**Comment by danlimao** [comment]
> Okay, your code is ALMOST there. :)
> 
> If you console.log(user) inside your "for" loop, you will notice that user is a string with the name of each property of the main object. Try doing that:
> 
> ```js
> for (let user in users) {
>   console.log(user) // it will print "Alan", and then "Jeff", and then...
> }
> ```
> 
> Now, on your if you are trying to access the property "online" for each user, which is the correct idea, but the execution is wrong. See:
> 
> ```js
> //the way you're doing
> if (users.user.online) { //this is expecting an object that looks like this: users{ user:{ online: true } }
>   count++
> }
> ```
> 
> See? Since you're directly using user with dot notation, javascript understands that you're trying to access "user" property of the object "users". You have to use bracket notation to accomplish what you want, which is access the object's properties dynamically, like this:
> 
> ```js
> //the way you should do, using bracket notation
> if (users[user].online) { //this is expecting an object that looks like this: users{ name_of_user:{ online: true } }
>   count++
> }
> ```
> 
> You can see other ways of doing the same thing in here: https://zellwk.com/blog/looping-through-js-objects/
> 
> Keep it up.

Thank you so much bro, you've helped me a lot
