### ISSUE TITLE
Slice and Splice - FreeCodeCamp Problem

### ISSUE THREAD

**Issue by danlimao** [danlimao/Trouble-with-Codes#8]
function frankenSplice(arr1, arr2, n) {

  var result = arr2.slice(0, arr2.length)

  result.splice(n, 0, arr1);

  console.log(result)

  return result;
}

frankenSplice(["claw", "tentacle"], ["head", "shoulders", "knees", "toes"], 2)

**Comment by madnilo** [comment]
Your having a problem with this because Splice doesn't accept an array as the third argument. Instead you have to pass every item as parameters, one by one. 

You might think you have to write a for or a while loop for that. But there's one operator from ES6 that can do the trick for you. It's the "spread operator".

Leave your code just the same, but try to add "..." before "arr1" on your splice.

Make sure you review how the spread operator works.

Cheers,
Your favorite brother

**Comment by madnilo** [comment]
This line here was really smart

var result = arr2.slice(0, arr2.length)

Just wanted to add that you could have also done it like that:

let result = arr2.slice(0)

Awesome code. Congrats!
